### ISSUE TITLE
Create a GUI window

### ISSUE THREAD

**Issue by shawnBGU** [dorinma/GraphGeneratorTool#2]
- [x] input number of vertices
- [x] input number of objectives
- [x] choose [edges generating method](https://github.com/dorinma/GraphGeneratorTool/issues/3)
- [x] choose [edges weight method](https://github.com/dorinma/GraphGeneratorTool/issues/5)
- [x] checkbox of bi-directional or not
- [x] button to choose path of saved files
- [x] button to choose path to load files from [may be future implementation](https://github.com/dorinma/GraphGeneratorTool/issues/6)
- [x] button to generate the files
- [x] Leave a place for canvas or any other way to show the graphs/data
- [x] input of number of queries to be generated
- [x] choose [query generator methods](https://github.com/dorinma/GraphGeneratorTool/issues/4)
